### ISSUE TITLE
Non-trivial fitness functions

### ISSUE THREAD

**Issue by jrieffel** [davidmatthews1uvm/minimal_morph_search#1]
Let's say I have an arbitrary robot shape (designed by CPPN or otherwise), what's the simplest way to pop that shape into voxcraft-sim in order to get fitness?  I'm having trouble (at first glance) finding the glue.

**Comment by skriegman** [comment]
Hi @jrieffel, minimal_morph_search is simulator independent and only designs morphologies. Let's close this issue @davidmatthews1uvm. John, let's re-open this in a different repo.
